@startuml
title GoogleLogin - LoginRepository
autonumber
hide footbox

participant LoginService
participant LoginRepository #LightSeaGreen

LoginService -> LoginRepository : GoogleLogin( email, name )

    
    LoginRepository -> LoginRepository : Create new instance -> UserBo as userData

    LoginRepository -> LoginRepository : Create new instance -> SqlCommand as cmd by passing ("google_user_login",DBConnectionString)

    LoginRepository -> LoginRepository : Assign cmd.command as CommandType.StoredProcedure

    LoginRepository -> LoginRepository : Assign cmd.Parameter (email)

    LoginRepository -> LoginRepository : Assign cmd.Parameter (name)
    
    alt (DBConnectionString.State == ConnectionState.Closed)
        LoginRepository -> LoginRepository : DBConnectionString.Open()
    end

    LoginRepository -> LoginRepository : cmd.ExecuteNonQuery()
    
    LoginRepository -> LoginRepository : Create new instance -> SqlDataAdapter as adapter
    LoginRepository -> LoginRepository : Create new instance -> DataTable as dsRecords
    LoginRepository -> LoginRepository : adapter.Fill(dsRecords)
    LoginRepository -> LoginRepository : Assign All the Values from dsRecords to UserData 
    LoginRepository -> LoginRepository : DBConnectionString.Close()
    LoginRepository -> LoginService : Returns userData




==Pseudo Code==
hnote across
  
        ASSIGN UserBo = new userData()

        ASSIGN SqlCommand cmd = new SqlCommand("google_user_login",DBConnectionString)
        
        ASSIGN cmd.command = CommandType.StoredProcedure

        ASSIGN cmd.parameter[Email] = email

        ASSIGN cmd.parameter[name] = name
        
        IF DBConnectionString.State == ConnectionState.Closed
            DBConnectionString.Open()
        
        ASSIGN cmd.ExecuteNonQuery() 

        DBConnectionString.Close()

        ASSIGN DataTable dsRecords = new DataTable()
        ASSIGN SqlDataAdapter adapter = new SqlDataAdapter()
        adapter.Fill(dsRecords)

        ASSIGN dsRecords to userData

        **RETURN userData**
   
    
end note

@enduml