@startuml

title UserSignUp - SignupController
autonumber
hide footbox

Participant Request
participant SignupController
participant Utilites
participant SignupService

Request -> SignupController : Post/signup

alt (TRY)
    SignupController -> Utilites : Validate Auth Header
    Utilites -> SignupController : Return( True / False )

    alt ( Auth Header True)
        SignupController -> SignupService : _signupService.CreateAccount(UserData, googleUser)
        
        SignupService -> SignupController : Return bool

        alt#Yellow #LightGreen (Succes : 200)
            SignupController -> Request : ok 200 Return bool
        else #LightGoldenRodYellow (Exception at Service Level : 500)

            SignupController -> Request : server error 500 return empty
        end
    note left: Uses Extension Resolver Method to return response
    else #LightGoldenRodYellow
        SignupController -> Request :Return 401 - UnAuthorized 
    end

else #LightGoldenRodYellow (catch block)
    SignupController -> Request : Exception at Controller level - Server Error 500 return empty
end


==Pseudo Code==

hnote across
Http Authorized Post/signup

TRY

    IF Auth Header is Valid then

        ASSIGN ServiceResult<bool> signupResult = _signupService.CreateAccount(UserData, googleUser)
        ** RETURN signupResult.FinalResult() ** // extension resolver
    ELSE

        **Return StatusCode(401)**
CATCH

    Set Response Status Code = 500
    **Return JsonResult of new { message = e.message, data = null}**

end note



@enduml